---
services:
  postgres:
    image: postgres:18.3-alpine
    environment:
      POSTGRES_USER: testapp
      POSTGRES_PASSWORD: testapp
      POSTGRES_DB: testapp
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testapp -d testapp"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  testapp:
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    # image: ghcr.io/as3ii/k8s-testapp:v0.0.2
    build: .
    environment:
      DB_USER: testapp
      DB_PASSWORD: testapp
      DB_NAME: testapp
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "8080:8080"

volumes:
  postgres: {}
