---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: k8s-testapp
data:
  POSTGRES_DB: k8s-testapp
  POSTGRES_USER: k8s-testapp

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: k8s-testapp
stringData:
  POSTGRES_PASSWORD: super-secret-password
